name: Continuous Integration and Continuous Deployment
on:
  push:
    branches:
      - main
permissions:
  id-token: write # need this for OIDC  
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::019994626350:role/github-actions-rol
          role-session-name: api-testing
          aws-region: us-east-1
      - name: Install dependencies
        run: make install
      - name: download model
        run: . venv/bin/activate && make dvc-pull-model
      - name: Run tests
        run: . venv/bin/activate && python3 -m src.CLI test -c
      - name: Build Docker image
        run: make create-docker-image
      
