name: Continuous Integration and Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make install && source .venv/bin/activate
      - name: Run tests
        run: python3 -m src.CLI test -c
