name: Continuous Integration and Continuous Deployment
on:
  push:
    branches:
      - main
permissions:
  id-token: write # need this for OIDC  
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  ci_cd:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::019994626350:role/github-actions-rol
          role-session-name: api-testing
          aws-region: us-east-1
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: . venv/bin/activate && python3 -m src.CLI validation --acc-threshold 0.75
      - name: commit .dvc file changes
        run: |
          git config --global user.email "santiagoprado12@gmail.com"
          git config --global user.name "github-actions[bot]"
          git add model/model.pkl.dvc
          git commit -m "Updating model serialization"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{github.ref}}
